source 'http://rubygems.org'
gem 'thor'
gem 'aws-sdk'
gem 'drink-socially'
gem 'sinatra'
gem 'haml'
gem 'activesupport'
gem 'activemodel'
gem 'thin'
gem 'color-generator', :git => "https://github.com/gregfitz23/color-generator.git"